package.json
src/lists/mainnet.ts
src/lists/matic.ts

I added some new tokens to our list. I mostly just copied the same formatting from previous adds, and I drew all of my info from CoinGecko. Wasn't sure what token names were best to use so I defaulted to whatever CoinGecko or their websites used. Also, I pulled the token images from the SushiSwap repo when I could as opposed to the tiny CoinGecko images.
I only added the Matic tokens when they were verified on CoinGecko and available to exchange through something like Zapper.
DG has an updated contract address, so I added a new item on the list for the new address and converted the previous address to DG (Old).

Added 24 mainnet and 5 matic tokens

---

src/lists/mainnet.ts
src/lists/matic.ts

Added 10 mainnet tokens and 1 matic token

Added 10 mainnet tokens and 1 matic token

---

src/index.ts
src/lists/avalanche.ts

Adds tokenlist for Avalanche.
Issue #11

feat(avalanche.ts): adds tokenlist for avalanche

---

src/__tests__/index.test.tsx
src/lists/mainnet.ts
src/lists/matic.ts

fix: Remove duplicates token. Minor edits

---

src/lists/mainnet.ts

Add token to Index Coop mainnet list
- dsETH
- gtcETH

feat: Add token dsETH and gtcETH to Index mainnet list

---

.github/workflows/publish.yml
src/lists/mainnet.ts

Add gala and blur tokens

---

src/lists/mainnet.ts

* Adds the wrapped tokens of 21co that will be used in ic21

feat: add 21co wrapped tokens

---

package.json
src/lists/mainnet/index-tokens.ts
src/lists/mainnet/mainnet.ts

* Adds ic21 index token
* Adds cdETI
* Adds new components for dsETH: [0xA35b1B31Ce002FBF2058D22F30f95D405200A15b](), [0xf951E335afb289353dc249e82926178EaC7DEd78](https://etherscan.io/token/0xf951e335afb289353dc249e82926178eac7ded78)

feat: add new tokens

---

package.json
src/__tests__/index.test.tsx
src/index.ts
src/lists/mainnet/index.ts

* Removes default export which messed up importing the mainnet tokens

fix: exports

---

src/lists/mainnet/index-tokens.ts

feat: add new 2x tokens

---

src/__tests__/utils.test.ts
src/utils/index.ts

* Adds util function to get index token data by symbol (and chainId)

feat: add utils

---

package-lock.json
package.json

Fixes the node engine requirement.

fix(package.json): Node engine requirement

---

src/__tests__/utils.test.ts
src/index.ts
src/lists/arbitrum/arbitrum.ts
src/lists/arbitrum/index-tokens.ts
src/lists/arbitrum/index.ts
src/types.ts
src/utils/index.ts

* Adds Index Arbitrum tokens
* Updates Arbitrum tokens
---
* ETH2X: https://arbiscan.io/address/0x67d2373f0321cd24a1b58e3c81fc1b6ef15b205c
* ETH3X: https://arbiscan.io/address/0x0bef95Cc308027C9a754D7674DE0844AE1dcD5b1
* iETH1X: https://arbiscan.io/token/0xaa61DDA963d0Cf89dA3C13FE635C84a1B8B6B988
* iBTC1X: https://arbiscan.io/token/0xCaD2B03e289260cCF59209CF059778342d1Cf33b
* BTC2X: https://arbiscan.io/address/0xfa69F1e2e48B411b98a105fb693fb381764Dc857
* BTC3X: https://arbiscan.io/token/0x53765a7cF4933bc939e32fA560FFf3D8E1d63473

feat: update arbitrum

---

src/lists/mainnet/mainnet.ts

https://www.coingecko.com/en/coins/beam-2
https://etherscan.io/token/0x62D0A8458eD7719FDAF978fe5929C6D342B0bFcE

feat: Add BEAM

---

src/__tests__/utils.test.ts
src/lists/arbitrum/index-tokens.ts

Match updated contracts mentioned here: https://github.com/IndexCoop/index-deployments/pull/274#issue-2310873583

chore: Update leverage token contracts

---

src/lists/mainnet/mainnet.ts

feat: hyETH components

---

src/lists/mainnet/index-tokens.ts

* Adds new Index token RWA: https://etherscan.io/address/0x7f5f1A44dd6f88cCb54Fe879e144dF644A4aDa24

feat: add rwa

---

src/lists/mainnet/mainnet.ts

* Adds Morpho's [Re7 WETH](https://etherscan.io/address/0x78fc2c2ed1a4cdb5402365934ae5648adad094d0) in prep for the upcoming hyETH rebalance

feat: add morpho re7 weth

---

src/__tests__/utils.test.ts
src/utils/index.ts

* Adds utility functions for getting any token by address or symbol

feat: add tokenlist utils

---

src/index.ts
src/lists/base/base.ts
src/lists/base/index-tokens.ts
src/lists/base/index.ts

* Adds new leverage + currency tokens for Base

feat: add base

---

src/lists/mainnet/mainnet.ts

feat: add components for usdcy

---

src/lists/base/index-tokens.ts
src/lists/mainnet/index-tokens.ts

* Updates icUSD to final values
* Adds version on Base too

feat: add icusd

---

src/lists/mainnet/mainnet.ts

https://etherscan.io/token/0x7aa68e84bcd8d1b4c9e10b1e565db993f68a3e09

feat: add new pendle position for hyeth

---

src/tokenlist.json.ts

* Adds deprecated tokens DATA and GMI

feat: add data and gmi

---

src/tokenlist.json.ts

* Adds new ratio tokens on Arbitrum: [BTC2xETH](https://arbiscan.io/token/0x77F69104145f94a81cEC55747C7a0Fc9CB7712C3) and [ETH2xBTC](https://arbiscan.io/token/0xE7b1Ce8DfEE3D7417397cd4f56dBFc0d49E43Ed1)

feat: add ratio tokens

---

config/networks.ts
src/tokenlist.json.ts

Adds components for FLIs on Polygon.

feat: add polygon components

---

src/tokenlist.json.ts

* Adds deprecated Polygon FLI tokens

feat: add deprecated polygon fli tokens

---

src/tokenlist.json.ts

Updates to the new Morpho [vault](https://etherscan.io/token/0x701907283a57ff77e255c3f1aad790466b8ce4ef#code) that serves as the single hyETH component.
⚠️ Merge only once hyETH is rebalance into this new vault. ⚠️ 
Then...

feat: update hyeth morpho vault

---

src/tokenlist.json.ts

* Adds [Re7USDC](https://app.morpho.org/vault?vault=0x12AFDeFb2237a5963e7BAb3e2D46ad0eee70406e&network=base)
* Adds [cbBTC](https://basescan.org/token/0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf)

feat: add re7usdc

---

src/tokenlist.json.ts

Updates some tokens that should be marked dangerous.

feat: update dangerous tokens

---

src/tokenlist.json.ts

Adds new product tokens and their component tokens (if missing):
* uSol2x: https://basescan.org/address/0x0A0Fbd86d2dEB53D7C65fecF8622c2Fa0DCdc9c6
* uSol3x: https://basescan.org/address/0x16c469F88979e19A53ea522f0c77aFAD9A043571
* uSui2x: https://basescan.org/address/0x2F67e4bE7fBF53dB88881324AAc99e9D85208d40
* uSui3x: https://basescan.org/address/0x8D08CE52e217aD61deb96dFDcf416B901cA2dC22#code
* wstETH15x: https://basescan.org/token/0xc8df827157adaf693fcb0c6f305610c28de739fd

feat: add uSol2x, uSol3x, uSui2x, uSui3x, wstETH15x
